export const bucketMap = new Set([
    "foundry:adamantium_bucket",
    "foundry:aluminium_bucket",
    "foundry:brass_bucket",
    "foundry:copper_bucket",
    "foundry:diamond_bucket",
    "foundry:dragon_steel_bucket",
    "foundry:gold_bucket",
    "foundry:iron_bucket",
    "foundry:lead_bucket",
    "foundry:netherite_bucket",
    "foundry:obsidian_bucket",
    "foundry:osmium_bucket",
    "foundry:palladium_bucket",
    "foundry:zinc_bucket",
    "foundry:redstone_bucket",
    "foundry:silver_bucket",
    "foundry:steel_bucket",
    "foundry:titanium_bucket"
]);
export const playerInputItemsIntoFoundry = new Map([
    ["minecraft:lava_bucket", { materialNumber: 1, layersToFill: 9 }],
    ["minecraft:iron_ingot", { materialNumber: 2, layersToFill: 1 }],
    ["foundry:iron_bucket", { materialNumber: 2, layersToFill: 9 }],
    ["minecraft:gold_ingot", { materialNumber: 3, layersToFill: 1 }],
    ["foundry:gold_bucket", { materialNumber: 3, layersToFill: 9 }],
    ["minecraft:copper_ingot", { materialNumber: 4, layersToFill: 1 }],
    ["foundry:copper_bucket", { materialNumber: 4, layersToFill: 9 }],
    ["minecraft:diamond", { materialNumber: 5, layersToFill: 1 }],
    ["foundry:diamond_bucket", { materialNumber: 5, layersToFill: 9 }],
    ["minecraft:netherite_ingot", { materialNumber: 6, layersToFill: 1 }],
    ["foundry:netherite_bucket", { materialNumber: 6, layersToFill: 9 }],
    ["minecraft:obsidian", { materialNumber: 7, layersToFill: 1 }],
    ["foundry:obsidian_bucket", { materialNumber: 7, layersToFill: 9 }],
    ["foundry:aluminium_ingot", { materialNumber: 8, layersToFill: 1 }],
    ["foundry:aluminium_bucket", { materialNumber: 8, layersToFill: 9 }],
    ["foundry:zinc_ingot", { materialNumber: 9, layersToFill: 1 }],
    ["foundry:zinc_bucket", { materialNumber: 9, layersToFill: 9 }],
    ["foundry:osmium_ingot", { materialNumber: 10, layersToFill: 1 }],
    ["foundry:osmium_bucket", { materialNumber: 10, layersToFill: 9 }],
    ["foundry:titanium_ingot", { materialNumber: 11, layersToFill: 1 }],
    ["foundry:titanium_bucket", { materialNumber: 11, layersToFill: 9 }],
    ["foundry:lead_ingot", { materialNumber: 12, layersToFill: 1 }],
    ["foundry:lead_bucket", { materialNumber: 12, layersToFill: 9 }],
    ["foundry:silver_ingot", { materialNumber: 13, layersToFill: 1 }],
    ["foundry:silver_bucket", { materialNumber: 13, layersToFill: 9 }],
    ["foundry:brass_ingot", { materialNumber: 14, layersToFill: 1 }],
    ["foundry:brass_bucket", { materialNumber: 14, layersToFill: 9 }],
    ["foundry:steel_ingot", { materialNumber: 15, layersToFill: 1 }],
    ["foundry:steel_bucket", { materialNumber: 15, layersToFill: 9 }],
    ["foundry:dragon_steel_ingot", { materialNumber: 16, layersToFill: 1 }],
    ["foundry:dragon_steel_bucket", { materialNumber: 16, layersToFill: 9 }],
    ["minecraft:redstone", { materialNumber: 17, layersToFill: 1 }],
    ["foundry:redstone_bucket", { materialNumber: 17, layersToFill: 9 }],
    ["foundry:palladium_ingot", { materialNumber: 18, layersToFill: 1 }],
    ["foundry:palladium_bucket", { materialNumber: 18, layersToFill: 9 }],
    ["foundry:adamantium_ingot", { materialNumber: 19, layersToFill: 1 }],
    ["foundry:adamantium_bucket", { materialNumber: 19, layersToFill: 9 }],
    // Raw ores fill 2 layers                           
    ["minecraft:raw_iron", { materialNumber: 2, layersToFill: 2 }],
    ["minecraft:raw_gold", { materialNumber: 3, layersToFill: 2 }],
    ["minecraft:raw_copper", { materialNumber: 4, layersToFill: 2 }],
]);
