export const bucketMap = new Map([
    ["foundry:molten_steel_obsidian_bucket", { giveItem: "foundry:3_quarter_molten_steel_obsidian_bucket" }],
    ["foundry:3_quarter_molten_steel_obsidian_bucket", { giveItem: "foundry:half_molten_steel_obsidian_bucket" }],
    ["foundry:half_molten_steel_obsidian_bucket", { giveItem: "foundry:quarter_molten_steel_obsidian_bucket" }],
    ["foundry:quarter_molten_steel_obsidian_bucket", { giveItem: "foundry:obsidian_bucket" }],
]);
export const playerInputItemsIntoFoundry = new Map([
    ["minecraft:lava_bucket", { materialNumber: 1, layersToFill: 1 }],
    ["minecraft:iron_ingot", { materialNumber: 2, layersToFill: 1 }],
    ["minecraft:gold_ingot", { materialNumber: 3, layersToFill: 1 }],
    ["minecraft:copper_ingot", { materialNumber: 4, layersToFill: 1 }],
    ["minecraft:diamond", { materialNumber: 5, layersToFill: 1 }],
    ["minecraft:netherite_ingot", { materialNumber: 6, layersToFill: 1 }],
    ["minecraft:obsidian", { materialNumber: 7, layersToFill: 1 }],
    ["foundry:aluminium_ingot", { materialNumber: 8, layersToFill: 1 }],
    ["foundry:zinc_ingot", { materialNumber: 9, layersToFill: 1 }],
    ["foundry:osmium_ingot", { materialNumber: 10, layersToFill: 1 }],
    ["foundry:titanium_ingot", { materialNumber: 11, layersToFill: 1 }],
    ["foundry:lead_ingot", { materialNumber: 12, layersToFill: 1 }],
    ["foundry:silver_ingot", { materialNumber: 13, layersToFill: 1 }],
    ["foundry:brass_ingot", { materialNumber: 14, layersToFill: 1 }],
    ["foundry:steel_ingot", { materialNumber: 15, layersToFill: 1 }],
    ["foundry:molten_steel_obsidian_bucket", { materialNumber: 15, layersToFill: 1 }],
    ["foundry:3_quarter_molten_steel_obsidian_bucket", { materialNumber: 15, layersToFill: 1 }],
    ["foundry:half_molten_steel_obsidian_bucket", { materialNumber: 15, layersToFill: 1 }],
    ["foundry:quarter_molten_steel_obsidian_bucket", { materialNumber: 15, layersToFill: 1 }],
    ["foundry:dragon_steel_ingot", { materialNumber: 16, layersToFill: 1 }],
    ["minecraft:redstone", { materialNumber: 17, layersToFill: 1 }],
    ["foundry:palladium_ingot", { materialNumber: 18, layersToFill: 1 }],
    ["foundry:adamantium_ingot", { materialNumber: 19, layersToFill: 1 }],
    // Raw ores fill 2 layers                           
    ["minecraft:raw_iron", { materialNumber: 2, layersToFill: 2 }],
    ["minecraft:raw_gold", { materialNumber: 3, layersToFill: 2 }],
    ["minecraft:raw_copper", { materialNumber: 4, layersToFill: 2 }],
]);
